spring.application.name=UcakBiletOtamasyonu
security.jwt.secret-key=JfVoLB61pmyKbWswGsuxD6TMnPFZzsoOACmSd1mA5hM=
security.cookie.secure=${COOKIE_SECURE:false}

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:gizlisifrem}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=UcakBiletOtamasyonu
