spring:
  config:
    import: "optional:file:./.env[.properties]"
  application:
    name: UcakBiletOtamasyonu
  security:
    oauth2:
      client:
        registration:
          google-login:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:gizlisifrem}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: UcakBiletOtamasyonu
  ai:
    model:
      chat: openai
      audio:
        transcription: openai
        speech: openai
    openai:
      api-key: ${OPENAI_API_KEY:}
      # api-base-url: ${OPENAI_API_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
      audio:
        transcription:
          options:
            model: gpt-4o-mini-transcribe
            response-format: text
            temperature: 0
        speech:
          options:
            model: gpt-4o-mini-tts
            voice: nova
            response-format: mp3

security:
  jwt:
    secret-key: JfVoLB61pmyKbWswGsuxD6TMnPFZzsoOACmSd1mA5hM=
  cookie:
    secure: ${COOKIE_SECURE:false}
